Update godot-build-debug.yml

diff --git a/.github/workflows/godot-build-debug.yml b/.github/workflows/godot-build-debug.yml
--- a/.github/workflows/godot-build-debug.yml
+++ b/.github/workflows/godot-build-debug.yml
@@ -28,8 +28,6 @@ jobs:
       image: barichello/godot-ci:${{ needs.set_tag.outputs.godot_ci_tag }}
     env:
       WINDOWS_PRESET: Windows Desktop
-      BUILD_ERRORS: > 
-        ( "ERROR: Can't open project" "ERROR: Cannot export project" )
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -44,20 +42,17 @@ jobs:
         run: |
           mkdir -v -p ${PROJECT_PATH}/build/windows
           godot -v --path $PROJECT_PATH --headless --export-debug "${WINDOWS_PRESET}" build/windows/$EXPORT_NAME.exe | tee $EXPORT_NAME.output
-      - name: Check for errors
+      - name: Check for possible errors
         run: |
-          #!/bin/bash
-          i=0
-          max=2
-          while [ $i -lt $max ]
-          do
-            if grep -q "${BUILD_ERRORS[$i]}" $EXPORT_NAME.output
-            then
-              echo "Found error ${BUILD_ERRORS[$i]} in Godot build output"
-              exit 1
-            fi
-            i=$(( i + 1 ))
-          done
+          if grep -q "ERROR: Can't open project" $EXPORT_NAME.output
+          then
+            echo "Found error 'ERROR: Can't open project' in Godot build output"
+            exit 1
+          elif grep -q "ERROR: Cannot export project" $EXPORT_NAME.output
+          then
+            echo "Found error 'ERROR: Cannot export project' in Godot build output"
+            exit 1  
+          fi
       - name: Upload windows artifact
         uses: actions/upload-artifact@v3.1.0
         with:
@@ -81,8 +76,6 @@ jobs:
 
             const allArtifacts = res.data.artifacts
                     .sort( (a,b) => (new Date(a.created_at)) - (new Date(b.created_at)) );
-
-            //console.log(JSON.stringify(allArtifacts));
 
             const artifactsToDelete = allArtifacts
                     .slice(0, -${{ env.NUM_OF_HISTORICAL_ARTIFACTS_TO_KEEP }})
