Update godot-build-debug.yml

diff --git a/.github/workflows/godot-build-debug.yml b/.github/workflows/godot-build-debug.yml
--- a/.github/workflows/godot-build-debug.yml
+++ b/.github/workflows/godot-build-debug.yml
@@ -26,6 +26,10 @@ jobs:
     needs: set_tag
     container:
       image: barichello/godot-ci:${{ needs.set_tag.outputs.godot_ci_tag }}
+    env:
+      WINDOWS_PRESET: Windows Desktop
+      BUILD_ERRORS: > 
+        ( "ERROR: Can't open project" )
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -39,7 +43,16 @@ jobs:
       - name: Build for windows
         run: |
           mkdir -v -p ${PROJECT_PATH}/build/windows
-          godot --rendering-driver opengl3 -v --path $PROJECT_PATH --no-window --export-debug "Windows Desktop" build/windows/$EXPORT_NAME.exe         
+          godot -v --path $PROJECT_PATH --headless --export-debug "${WINDOWS_PRESET}" build/windows/$EXPORT_NAME.exe > $EXPORT_NAME.output
+      - name: Check for errors
+        run: |
+          for error in ${BUILD_ERRORS[@]}; do
+            if grep -q $error $EXPORT_NAME.output
+            then
+              echo "Found error \"$error\" in Godot build output"
+              exit 1
+            fi
+          done
       - name: Upload windows artifact
         uses: actions/upload-artifact@v3.1.0
         with:
