First complete version of godot builder workflow

diff --git a/.github/workflows/godot_build.yml b/.github/workflows/godot_build.yml
--- a/.github/workflows/godot_build.yml
+++ b/.github/workflows/godot_build.yml
@@ -7,12 +7,46 @@ on:
         type: boolean
         required: false
         default: true
+      godot_version:
+        type: string
+        required: true 
+      export_name:
+        type: string
+        required: true 
+        description: The name of the exported binary (appended with '-debug' if debug is set to true)
+      windows:
+        type: boolean
+        required: false 
+        default: true
+        description: Should a Windows binary be generated
+      windows_preset:
+        type: string
+        required: false 
+        default: 'Windows Desktop'  
+      linux:
+        type: boolean
+        required: false 
+        default: true
+        description: Should a Linux binary be generated
+      linux_preset:
+        type: string
+        required: false 
+        default: 'Linux/X11 Desktop'          
+      project_path:
+        type: string
+        required: false 
+        default: '.'
+      export_presets_path:
+        type: string
+        required: false 
+        default: '.'
+        description: Relative to the project path
         
 env:
-  GODOT_VERSION: 4.1
-  EXPORT_NAME: "${{ github.event.repository.name }}-debug"
-  PROJECT_PATH: "."
-  NUM_OF_HISTORICAL_ARTIFACTS_TO_KEEP: 1
+  GODOT_VERSION: ${{ inputs.godot_version }}
+  EXPORT_NAME: ${{ export_name }}${{ inputs.debug && '-debug' || '' }}
+  PROJECT_PATH: ${{ inputs.project_path }}
+  EXPORT_PRESETS_PATH: ${{ inputs.export_presets_path }}
 
 jobs:
   set_tag:
@@ -24,9 +58,10 @@ jobs:
       - id: set_tag
         run: echo "tag=$GODOT_VERSION" >> $GITHUB_OUTPUT
         
-  export:
-    name: Export from Godot
+  windows_export:
+    name: Export for Windows
     runs-on: ubuntu-latest
+    if: windows
     defaults:
       run:
         shell: bash
@@ -34,7 +69,8 @@ jobs:
     container:
       image: barichello/godot-ci:${{ needs.set_tag.outputs.godot_ci_tag }}
     env:
-      WINDOWS_PRESET: Windows Desktop
+      WINDOWS_PRESET: ${{ inputs.windows_preset }}
+      DEBUG: ${{ inputs.debug }}
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -44,11 +80,14 @@ jobs:
         run: |
           mkdir -v -p ~/.local/share/godot/export_templates
           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
-          # cp .github/workflows/export_presets.cfg ${PROJECT_PATH}/export_presets.cfg
+          mv $PROJECT_PATH/$EXPORT_PRESETS_PATH/export_presets.cfg $PROJECT_PATH
       - name: Build for windows
         run: |
           mkdir -v -p ${PROJECT_PATH}/build/windows
-          godot -v --path $PROJECT_PATH --headless --export-debug "${WINDOWS_PRESET}" build/windows/$EXPORT_NAME.exe | tee $EXPORT_NAME.output
+          godot_command=(godot -v --path $PROJECT_PATH --headless)
+          if $DEBUG == 'true'; then godot_command+=(--export-debug); else godot_command+=(--export-release); fi;
+          godot_command+=($PROJECT_PATH/build/windows/$EXPORT_NAME.exe | tee $EXPORT_NAME.output)
+          "${godot_command[@]}"
       - name: Check for build errors
         shell: bash
         run: |
@@ -66,38 +105,51 @@ jobs:
         with:
           name: windows-${{ env.EXPORT_NAME }}
           path: ${{ env.PROJECT_PATH }}/build/windows
-
-  clean:
-    name: Cleanup Old Artifacts
+          
+  linux_export:
+    name: Export for Linux
     runs-on: ubuntu-latest
-    needs: export
+    if: linux
+    defaults:
+      run:
+        shell: bash
+    needs: set_tag
+    container:
+      image: barichello/godot-ci:${{ needs.set_tag.outputs.godot_ci_tag }}
+    env:
+      LINUX_PRESET: ${{ inputs.linux_preset }}
+      DEBUG: ${{ inputs.debug }}
     steps:
-      - name: Find and delete old artifacts
-        uses: actions/github-script@v6
-        id: delete-artifacts
+      - name: Checkout
+        uses: actions/checkout@v3
         with:
-          script: |
-            const res = await github.rest.actions.listArtifactsForRepo({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-            })
-
-            const allArtifacts = res.data.artifacts
-                    .sort( (a,b) => (new Date(a.created_at)) - (new Date(b.created_at)) );
-
-            const artifactsToDelete = allArtifacts
-                    .slice(0, -${{ env.NUM_OF_HISTORICAL_ARTIFACTS_TO_KEEP }})
-                    .filter(({ name }) => name.endsWith('${{ env.EXPORT_NAME }}'))
-
-            artifactsToDelete.forEach(({ id }) => {
-               github.rest.actions.deleteArtifact({
-                 owner: context.repo.owner,
-                 repo: context.repo.repo,
-                 artifact_id: id,
-               })
-              })
-              
-            return artifactsToDelete
-            
-      - name: Print deleted artifacts
-        run: echo "${{steps.delete-artifacts.outputs.result}}"
+          lfs: true          
+      - name: Setup
+        run: |
+          mkdir -v -p ~/.local/share/godot/export_templates
+          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
+          mv $PROJECT_PATH/$EXPORT_PRESETS_PATH/export_presets.cfg $PROJECT_PATH
+      - name: Build for windows
+        run: |
+          mkdir -v -p ${PROJECT_PATH}/build/linux
+          godot_command=(godot -v --path $PROJECT_PATH --headless)
+          if $DEBUG == 'true'; then godot_command+=(--export-debug); else godot_command+=(--export-release); fi;
+          godot_command+=($PROJECT_PATH/build/linux/$EXPORT_NAME.exe | tee $EXPORT_NAME.output)
+          "${godot_command[@]}"
+      - name: Check for build errors
+        shell: bash
+        run: |
+          BUILD_ERRORS=("ERROR: Can't open project" "ERROR: Cannot export project")
+          for ((i = 0; i < ${#BUILD_ERRORS[@]}; i++))
+          do
+            if grep -q "${BUILD_ERRORS[$i]}" $EXPORT_NAME.output
+            then
+              echo "Found error ${BUILD_ERRORS[$i]} in Godot build output"
+              exit 1
+            fi
+          done
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: linux-${{ env.EXPORT_NAME }}
+          path: ${{ env.PROJECT_PATH }}/build/linux
